[theme]
base = "dark"
primaryColor = "#8b5cf6"
backgroundColor = "#060913"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
